apiVersion: v1  
kind: Service
metadata:
  name: simple-node-service
  namespace: simple-node
spec:
  selector: 
    app: simple-node-server
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      NodePort: 30015