apiVersion: v1  
kind: Service
metadata:
  name: simple-node-service
  namespace: dev
spec:
  selector: 
    app: simple-node-server
  # type: NodePort
  ports:
    - port: 3000
      targetPort: 3000